### ISSUE TITLE
Rewrite the Relay documentation / oper guide

### ISSUE THREAD

**Issue by jlu5** [jlu5/PyLink#619]
The current guide in `docs/pylink-opers.md` is fairly outdated - for example, we don't enforce nick tags anymore, LINKACL whitelists are supported in 2.0, ...

Really, the relay documentation should not only list the must-know commands but also describe in detail how more abstract concepts like CLAIM work internally.

Another thing worth adding is a general overview of how the Relay system works - either as part of this document, the FAQ, or a separate page entirely. My rationale is that not everyone is familiar with Janus, and referring solely to an unmaintained piece of software as the basis of "Relay" is not informative.

We should also fit in common questions that curious folk have poked me on IRC about: e.g.
- How are kills, g/k/zlines, (ext)bans, etc. handled?
- How does PyLink map modes between the plethora of IRCds we support? / how are modes supported on one IRCd but not on another dealt with?

----

A rough checklist:
- [x] Document LINKACL whitelist
- [x] Describe CLAIM more thoroughly
- [x] Document CHANDESC (new in 2.0) 
- [x] ~~Document MODEDELTA (new in 2.0)~~ nah, too niche
- [x] Brainstorm and expand the relay FAQ (see above)
